# Generated by Django 6.0.7 on 2026-07-14 10:22

import apps.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('PLAYWRIGHT', 'Playwright'), ('CUCUMBER', 'Cucumber'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('raw_file', models.FileField(upload_to=apps.reports.models.report_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('failed_tests', models.PositiveIntegerField(default=0)),
                ('skipped_tests', models.PositiveIntegerField(default=0)),
                ('total_duration', models.FloatField(default=0.0)),
                ('parser_version', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_runs', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_report_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('feature', models.CharField(blank=True, max_length=255)),
                ('suite', models.CharField(blank=True, max_length=255)),
                ('scenario', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('duration', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reportrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['project', 'created_at'], name='reports_rep_project_d7e711_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['status'], name='reports_rep_status_f320b8_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['report_run', 'status'], name='reports_tes_report__32a62d_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['scenario'], name='reports_tes_scenari_515295_idx'),
        ),
    ]
