# Generated by Django 6.0.7 on 2026-07-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrun',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
